/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ColorPaletteEntry, Product, FAQItem } from './types';

export const COLOR_PALETTE: ColorPaletteEntry[] = [
  {
    id: 'toucan-orange',
    nameEs: 'Naranja Tucán',
    nameEn: 'Toucan Orange',
    hex: '#F97316',
    categoryEs: 'Paleta Exótica',
    categoryEn: 'Exotic Palette',
    descriptionEs: 'Un naranja sumamente energético y cálido inspirado en el pico de nuestro tucán.',
    descriptionEn: 'An energetic and warm orange inspired by our toucan\'s iconic bill.',
    isToucanColor: true
  },
  {
    id: 'tropical-yellow',
    nameEs: 'Amarillo Tropical',
    nameEn: 'Tropical Yellow',
    hex: '#FACC15',
    categoryEs: 'Paleta Exótica',
    categoryEn: 'Exotic Palette',
    descriptionEs: 'Luminoso y vibrante como el sol de la selva ecuatorial, perfecto para crear ambientes llenos de vida.',
    descriptionEn: 'Bright and vibrant like the equatorial jungle sun, perfect for creating lively spaces.',
    isToucanColor: true
  },
  {
    id: 'coral-red',
    nameEs: 'Rojo Coral',
    nameEn: 'Coral Red',
    hex: '#EF4444',
    categoryEs: 'Paleta Exótica',
    categoryEn: 'Exotic Palette',
    descriptionEs: 'El atrevido y pasional matiz rojo que acentúa las puntas del plumaje y pico del tucán.',
    descriptionEn: 'The bold, passionate red hue that highlights the tips of the toucan\'s features.',
    isToucanColor: true
  },
  {
    id: 'jungle-cyan',
    nameEs: 'Celeste Selva',
    nameEn: 'Jungle Cyan',
    hex: '#06B6D4',
    categoryEs: 'Paleta Exótica',
    categoryEn: 'Exotic Palette',
    descriptionEs: 'Un celeste refrescante e innovador, inspirado en los destellos magnéticos alrededor de los ojos de nuestro tucán.',
    descriptionEn: 'A refreshing and innovative light blue, inspired by the magnetic glow around our toucan\'s eyes.',
    isToucanColor: true
  },
  {
    id: 'ocean-blue',
    nameEs: 'Azul Marino Colormar',
    nameEn: 'Colormar Deep Blue',
    hex: '#1E3A8A',
    categoryEs: 'Clásicos Imperiales',
    categoryEn: 'Imperial Classics',
    descriptionEs: 'Elegante, equilibrado y profundo. Ideal para fachadas sofisticadas y paredes de acento.',
    descriptionEn: 'Elegant, balanced, and deep. Ideal for sophisticated facades and accent walls.',
  },
  {
    id: 'emerald-forest',
    nameEs: 'Verde Esmeralda',
    nameEn: 'Emerald Forest',
    hex: '#10B981',
    categoryEs: 'Naturaleza Orgánica',
    categoryEn: 'Organic Nature',
    descriptionEs: 'Un tono orgánico y pacífico que imita la opulencia de la vegetación selvática húmeda.',
    descriptionEn: 'An organic and peaceful shade echoing the richness of the wet rainforest canopy.',
  },
  {
    id: 'concrete-gray',
    nameEs: 'Gris Cemento',
    nameEn: 'Concrete Gray',
    hex: '#94A3B8',
    categoryEs: 'Minimalismo Urbano',
    categoryEn: 'Urban Minimalism',
    descriptionEs: 'El equilibrio industrial perfecto. Refinado, moderno y altamente versátil para interiores vanguardistas.',
    descriptionEn: 'The perfect industrial balance. Refined, modern, and highly versatile for vanguard interiors.',
  },
  {
    id: 'pure-alabaster',
    nameEs: 'Blanco Alabastro',
    nameEn: 'Alabaster White',
    hex: '#F8FAFC',
    categoryEs: 'Minimalismo Urbano',
    categoryEn: 'Urban Minimalism',
    descriptionEs: 'Un blanco puro y luminoso que multiplica el rebote de la luz natural de tus estancias.',
    descriptionEn: 'A pure, luminous white that multiplies natural light bounce inside your rooms.',
  }
];

export const PRODUCTS: Product[] = [
  {
    id: 'prod-0',
    nameEs: 'Cutter Profesional Total',
    nameEn: 'Total Professional Utility Knife',
    category: 'paints',
    descriptionEs: 'Cuchilla retráctil de alta resistencia para cortes precisos en cartón, plástico y otros materiales.',
    descriptionEn: 'Heavy-duty retractable utility knife for precise cuts in cardboard, plastic, and other materials.',
    price: 44.52,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.2,
    reviewsCount: 227,
    image: '/productIMG/1772643756103.png',
    featured: true,
    stock: 64
  },
  {
    id: 'prod-1',
    nameEs: 'Pegatanke Soldadura al Frío Epoxi',
    nameEn: 'Pegatanke Cold Epoxy Weld',
    category: 'paints',
    descriptionEs: 'Pegamento epóxico de dos componentes, ideal para reparaciones de alta resistencia en diversas superficies.',
    descriptionEn: 'Two-component epoxy adhesive, ideal for high-resistance repairs on multiple surfaces.',
    price: 16.18,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 270,
    image: '/productIMG/1772643877934.png',
    featured: true,
    stock: 25
  },
  {
    id: 'prod-2',
    nameEs: 'Thinner Acrílico Quiminter',
    nameEn: 'Quiminter Acrylic Thinner',
    category: 'paints',
    descriptionEs: 'Solvente de alta pureza para dilución de pinturas acrílicas.',
    descriptionEn: 'High-purity solvent for acrylic paint dilution.',
    price: 40.17,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 207,
    image: '/productIMG/1772644108859.png',
    featured: true,
    stock: 21
  },
  {
    id: 'prod-3',
    nameEs: 'Magic Gypsum Mastique Todo Propósito',
    nameEn: 'Magic Gypsum All-Purpose Mastic',
    category: 'paints',
    descriptionEs: 'Mastique listo para usar, ideal para juntas de drywall y acabados de paredes interiores.',
    descriptionEn: 'Ready-to-use mastic joint compound, ideal for drywall and interior wall finishes.',
    price: 50.06,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 90,
    image: '/productIMG/1772644164759.png',
    featured: true,
    stock: 86
  },
  {
    id: 'prod-4',
    nameEs: 'Coloreal Cemento Plástico Tapa Goteras',
    nameEn: 'Coloreal Tapa Goteras Plastic Cement',
    category: 'paints',
    descriptionEs: 'Sellador asfáltico plástico de alta densidad para tapar goteras e impermeabilizar juntas.',
    descriptionEn: 'High-density asphalt plastic sealer to patch leaks and waterproof joints.',
    price: 25.46,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.9,
    reviewsCount: 290,
    image: '/productIMG/1772644234872.png',
    featured: true,
    stock: 20
  },
  {
    id: 'prod-5',
    nameEs: 'Manpica Sellador Antialcalino',
    nameEn: 'Manpica Anti-Alkaline Sealer',
    category: 'paints',
    descriptionEs: 'Sellador protector para paredes expuestas a la humedad y alcalinidad del cemento.',
    descriptionEn: 'Protective sealer for walls exposed to dampness and cement alkalinity.',
    price: 14.21,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.1,
    reviewsCount: 58,
    image: '/productIMG/1772644294053.png',
    featured: false,
    stock: 78
  },
  {
    id: 'prod-6',
    nameEs: 'Multilac Barniz para Muebles',
    nameEn: 'Multilac Furniture Varnish',
    category: 'paints',
    descriptionEs: 'Barniz protector para madera que proporciona brillo, durabilidad y un aroma agradable.',
    descriptionEn: 'Protective wood varnish that provides gloss, durability, and a pleasant scent.',
    price: 33.47,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.2,
    reviewsCount: 120,
    image: '/productIMG/1772644367078.png',
    featured: false,
    stock: 88
  },
  {
    id: 'prod-7',
    nameEs: 'Manpica Pasta Profesional para Drywall',
    nameEn: 'Manpica Joint Compound Wall Putty',
    category: 'paints',
    descriptionEs: 'Compuesto para juntas y encamisado de paredes de fácil aplicación y lijado rápido.',
    descriptionEn: 'Drywall joint compound and wall putty for easy application and fast sanding.',
    price: 23.75,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.4,
    reviewsCount: 22,
    image: '/productIMG/1772644410638.png',
    featured: false,
    stock: 57
  },
  {
    id: 'prod-8',
    nameEs: 'Manpica Pintura para Pizarra Verde',
    nameEn: 'Manpica Green Blackboard Paint',
    category: 'paints',
    descriptionEs: 'Pintura base agua que transforma cualquier superficie lisa en una pizarra escolar verde.',
    descriptionEn: 'Water-based paint that transforms any smooth surface into a green blackboard.',
    price: 34.53,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.4,
    reviewsCount: 187,
    image: '/productIMG/1772644482091.png',
    featured: false,
    stock: 48
  },
  {
    id: 'prod-9',
    nameEs: 'Solinux Pasta Profesional Blanca',
    nameEn: 'Solinux Professional White Putty',
    category: 'paints',
    descriptionEs: 'Masa niveladora de alta calidad para interiores y exteriores de acabado liso.',
    descriptionEn: 'High-quality smoothing and leveling putty for interior and exterior walls.',
    price: 16.98,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.5,
    reviewsCount: 113,
    image: '/productIMG/1772644534883.png',
    featured: false,
    stock: 66
  },
  {
    id: 'prod-10',
    nameEs: 'Manto Fácil Impermeabilizante Colores',
    nameEn: 'Manto Facil Color Roofing Sealer',
    category: 'paints',
    descriptionEs: 'Impermeabilizante líquido elastomérico para techos de aplicación directa y secado rápido.',
    descriptionEn: 'Elastomeric liquid roofing sealer for direct application and fast drying.',
    price: 11.71,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.9,
    reviewsCount: 217,
    image: '/productIMG/1772644596774.png',
    featured: false,
    stock: 85
  },
  {
    id: 'prod-11',
    nameEs: 'Coloreal Impermeabilizante Elastomérico',
    nameEn: 'Coloreal Elastomeric Waterproofing',
    category: 'paints',
    descriptionEs: 'Recubrimiento elástico hidrófobo que protege contra filtraciones y humedad extrema.',
    descriptionEn: 'Elastic hydrophobic coating that protects against leaks and extreme humidity.',
    price: 18.36,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 130,
    image: '/productIMG/1772644652214.png',
    featured: false,
    stock: 65
  },
  {
    id: 'prod-12',
    nameEs: 'Quimicolor Esmalte Sintético Rojo',
    nameEn: 'Quimicolor Red Synthetic Enamel',
    category: 'paints',
    descriptionEs: 'Esmalte brillante para metal y madera de gran resistencia y durabilidad al exterior.',
    descriptionEn: 'Gloss enamel for metal and wood with high resistance and exterior durability.',
    price: 15.22,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.2,
    reviewsCount: 173,
    image: '/productIMG/1772644713031.png',
    featured: false,
    stock: 83
  },
  {
    id: 'prod-13',
    nameEs: 'VP Pinturas Esmalte Metalizado',
    nameEn: 'VP Paints Metallic Enamel',
    category: 'paints',
    descriptionEs: 'Esmalte metalizado de bajo olor y secado rápido, ideal para acabados decorativos premium.',
    descriptionEn: 'Low-odor, quick-drying metallic enamel, ideal for premium decorative finishes.',
    price: 50.59,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.2,
    reviewsCount: 193,
    image: '/productIMG/1772644823755.png',
    featured: false,
    stock: 114
  },
  {
    id: 'prod-14',
    nameEs: 'Esmalte Martiluso Acabado Martillado',
    nameEn: 'Martiluso Hammertone Enamel',
    category: 'paints',
    descriptionEs: 'Pintura protectora anticorrosiva con acabado texturizado tipo martillado para metal.',
    descriptionEn: 'Anticorrosive protective paint with a textured hammertone finish for metal.',
    price: 42.01,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 184,
    image: '/productIMG/1772644893283.png',
    featured: false,
    stock: 48
  },
  {
    id: 'prod-15',
    nameEs: 'VP Pinturas Aluminio Difuso',
    nameEn: 'VP Paints Diffuse Aluminum Paint',
    category: 'paints',
    descriptionEs: 'Pintura protectora para superficies metálicas con excelente brillo aluminio y resistencia.',
    descriptionEn: 'Protective paint for metallic surfaces with excellent aluminum gloss and durability.',
    price: 20.46,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.1,
    reviewsCount: 249,
    image: '/productIMG/1772645013474.png',
    featured: false,
    stock: 59
  },
  {
    id: 'prod-16',
    nameEs: 'Quimicolor Negro Chasis Semi Mate',
    nameEn: 'Quimicolor Chassis Black Semi Matte',
    category: 'paints',
    descriptionEs: 'Esmalte protector formulado especialmente para chasis de vehículos con acabado semi mate.',
    descriptionEn: 'Protective enamel specially formulated for vehicle chassis with a semi-matte finish.',
    price: 27.25,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 5.0,
    reviewsCount: 164,
    image: '/productIMG/1772645068843.png',
    featured: false,
    stock: 117
  },
  {
    id: 'prod-17',
    nameEs: 'Sellador Blanco Catalizado para Madera',
    nameEn: 'Wood Catalyzed White Sealer',
    category: 'paints',
    descriptionEs: 'Sellador base de alto rendimiento y rápido lijado para la preparación de madera en interiores.',
    descriptionEn: 'High-performance, fast-sanding white sealer base for interior wood prep.',
    price: 31.17,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.8,
    reviewsCount: 200,
    image: '/productIMG/1772645167680.png',
    featured: false,
    stock: 32
  },
  {
    id: 'prod-18',
    nameEs: 'Laca Blanca Brillante Catalizada',
    nameEn: 'Wood Catalyzed Gloss White Lacquer',
    category: 'paints',
    descriptionEs: 'Acabado brillante catalizado de alta resistencia física y química para carpintería fina.',
    descriptionEn: 'Glossy catalyzed finish with high physical and chemical resistance for fine woodwork.',
    price: 55.32,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.4,
    reviewsCount: 152,
    image: '/productIMG/1772737414926.png',
    featured: false,
    stock: 26
  },
  {
    id: 'prod-19',
    nameEs: 'Cola Blanca para Madera',
    nameEn: 'White Wood Glue',
    category: 'paints',
    descriptionEs: 'Adhesivo de acetato de polivinilo de alta resistencia, ideal para ensamblar y pegar madera.',
    descriptionEn: 'High-resistance polyvinyl acetate adhesive, ideal for wood assembly and bonding.',
    price: 21.57,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 46,
    image: '/productIMG/1772737700379.png',
    featured: false,
    stock: 109
  },
  {
    id: 'prod-20',
    nameEs: 'Pegaphil Pegante para Madera',
    nameEn: 'Pegaphil Wood Glue',
    category: 'paints',
    descriptionEs: 'Pegante base agua de excelente adhesión y secado rápido para trabajos de carpintería.',
    descriptionEn: 'Water-based wood glue with excellent adhesion and fast drying for carpentry work.',
    price: 44.40,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 78,
    image: '/productIMG/1772737792843.png',
    featured: false,
    stock: 105
  },
  {
    id: 'prod-21',
    nameEs: 'Sellador Catalizado para Madera',
    nameEn: 'Wood Catalyzed Sealer',
    category: 'paints',
    descriptionEs: 'Sellador de dos componentes (base y catalizador) para acabados profesionales en madera.',
    descriptionEn: 'Two-component sealer (base and catalyst) for professional wood finishes.',
    price: 35.20,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.9,
    reviewsCount: 112,
    image: '/productIMG/1772737899052.png',
    featured: false,
    stock: 97
  },
  {
    id: 'prod-22',
    nameEs: 'Mulod Monocapa Blanco',
    nameEn: 'Mulod Monocapa White Paint',
    category: 'paints',
    descriptionEs: 'Pintura monocapa de alta cubrición y blancura excepcional para paredes interiores.',
    descriptionEn: 'High-coverage, exceptionally white single-coat paint for interior walls.',
    price: 53.50,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 296,
    image: '/productIMG/1772737967937.png',
    featured: false,
    stock: 50
  },
  {
    id: 'prod-23',
    nameEs: 'Mulod Chemicals Masilla Plástica',
    nameEn: 'Mulod Chemicals Plastic Putty',
    category: 'paints',
    descriptionEs: 'Masilla de relleno de alta calidad para reparaciones en la industria automotriz y doméstica.',
    descriptionEn: 'High-quality filler putty for repairs in automotive and household applications.',
    price: 14.64,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.5,
    reviewsCount: 161,
    image: '/productIMG/1772738076661.png',
    featured: false,
    stock: 49
  },
  {
    id: 'prod-24',
    nameEs: 'Mastique SPC',
    nameEn: 'SPC Mastic Joint Compound',
    category: 'paints',
    descriptionEs: 'Mastique listo para aplicar, ideal para juntas de paneles de yeso y nivelación de paredes.',
    descriptionEn: 'Ready-to-apply mastic compound, ideal for drywall joints and wall leveling.',
    price: 45.96,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.2,
    reviewsCount: 129,
    image: '/productIMG/1772738153356.png',
    featured: false,
    stock: 57
  },
  {
    id: 'prod-25',
    nameEs: 'Masa de Pulir Panthers Automotive',
    nameEn: 'Panthers Automotive Rubbing Compound',
    category: 'paints',
    descriptionEs: 'Compuesto pulidor base agua de alto corte para eliminar rayas y pulir pintura automotriz.',
    descriptionEn: 'High-cut water-based rubbing compound to remove scratches and polish automotive paint.',
    price: 24.71,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 257,
    image: '/productIMG/1772738246923.png',
    featured: false,
    stock: 53
  },
  {
    id: 'prod-26',
    nameEs: 'Cera en Pasta Panthers Paste Wax',
    nameEn: 'Panthers Carnauba Paste Wax',
    category: 'paints',
    descriptionEs: 'Cera protectora de carnauba que proporciona máximo brillo y protección contra rayos UV.',
    descriptionEn: 'Protective carnauba wax providing maximum gloss and protection against UV rays.',
    price: 15.09,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.5,
    reviewsCount: 278,
    image: '/productIMG/1772738324087.png',
    featured: false,
    stock: 64
  },
  {
    id: 'prod-27',
    nameEs: 'Symplex Piranha X1 Compuesto Pulidor',
    nameEn: 'Symplex Piranha X1 Hyper Cut Compound',
    category: 'paints',
    descriptionEs: 'Compuesto pulidor abrasivo de grado profesional sin silicona ni rellenos para talleres.',
    descriptionEn: 'Professional grade abrasive rubbing compound with no silicone or fillers for body shops.',
    price: 16.08,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.8,
    reviewsCount: 43,
    image: '/productIMG/1772738373979.png',
    featured: false,
    stock: 115
  },
  {
    id: 'prod-28',
    nameEs: 'Detailing Pro Sellador Líquido Ultra Brillo',
    nameEn: 'Detailing Pro Liquid Sealant Ultra Gloss',
    category: 'paints',
    descriptionEs: 'Sellador líquido de alto brillo para la protección de la pintura automotriz.',
    descriptionEn: 'High-gloss liquid sealant for the protection of automotive paint.',
    price: 20.20,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 202,
    image: '/productIMG/1772738428354.png',
    featured: false,
    stock: 56
  },
  {
    id: 'prod-29',
    nameEs: 'Ixell Pintura Automotriz',
    nameEn: 'Ixell Automotive Paint',
    category: 'paints',
    descriptionEs: 'Pintura original para el repintado automotriz profesional con excelente poder cubriente.',
    descriptionEn: 'Original automotive paint for professional car refinishing with excellent hiding power.',
    price: 45.56,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 74,
    image: '/productIMG/1772738497559.png',
    featured: false,
    stock: 34
  },
  {
    id: 'prod-30',
    nameEs: 'Maxytone MAK-100 Barniz de Alto Rendimiento',
    nameEn: 'Maxytone MAK-100 High Performance Clearcoat',
    category: 'paints',
    descriptionEs: 'Barniz transparente premium para acabados de alta resistencia en talleres automotrices.',
    descriptionEn: 'Premium clearcoat for high-resistance finishes in professional automotive shops.',
    price: 22.42,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.2,
    reviewsCount: 180,
    image: '/productIMG/1772738556537.png',
    featured: false,
    stock: 22
  },
  {
    id: 'prod-31',
    nameEs: 'Ixell Kit de Resina de Poliéster',
    nameEn: 'Ixell Polyester Resin Kit',
    category: 'paints',
    descriptionEs: 'Kit completo de resina de poliéster para reparaciones estructurales y moldeado plástico.',
    descriptionEn: 'Complete polyester resin kit for structural repairs and plastic molding.',
    price: 36.45,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 152,
    image: '/productIMG/1772738605164.png',
    featured: false,
    stock: 31
  },
  {
    id: 'prod-32',
    nameEs: 'Maxytone MAX-900 Barniz Mate',
    nameEn: 'Maxytone MAX-900 Matte Clearcoat',
    category: 'paints',
    descriptionEs: 'Barniz mate para el repintado automotriz profesional que ofrece un acabado de alta gama.',
    descriptionEn: 'Matte clearcoat for professional automotive refinishing offering a high-end finish.',
    price: 49.45,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.1,
    reviewsCount: 232,
    image: '/productIMG/1772738665880.png',
    featured: false,
    stock: 37
  },
  {
    id: 'prod-33',
    nameEs: 'Esmalte Alto Brillante para Interiores y Exteriores',
    nameEn: 'Gloss Enamel for Interior and Exterior',
    category: 'paints',
    descriptionEs: 'Esmalte alquídico de alto brillo y resistencia a la intemperie para madera y metal.',
    descriptionEn: 'High-gloss alkyd enamel with weather resistance for wood and metal.',
    price: 13.36,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 244,
    image: '/productIMG/1772738718822.png',
    featured: false,
    stock: 59
  },
  {
    id: 'prod-34',
    nameEs: 'Pinco DuraMax Esmalte Blanco',
    nameEn: 'Pinco DuraMax White Enamel',
    category: 'paints',
    descriptionEs: 'Esmalte brillante de alta resistencia y cobertura ideal para proteger y embellecer superficies.',
    descriptionEn: 'High-resistance gloss enamel with ideal coverage to protect and beautify surfaces.',
    price: 59.51,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 152,
    image: '/productIMG/1772738773998.png',
    featured: false,
    stock: 69
  },
  {
    id: 'prod-35',
    nameEs: 'Abramax Masilla para Madera Abrawood',
    nameEn: 'Abramax Abrawood Wood Putty Filler',
    category: 'paints',
    descriptionEs: 'Masilla acrílica lista para usar, ideal para resanar grietas y agujeros en madera.',
    descriptionEn: 'Ready-to-use acrylic putty, ideal for patching cracks and holes in woodwork.',
    price: 43.24,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 183,
    image: '/productIMG/1772846488149.png',
    featured: false,
    stock: 48
  },
  {
    id: 'prod-36',
    nameEs: 'Pintura Cromas Industrial Epóxica',
    nameEn: 'Cromas Industrial Epoxy Paint',
    category: 'paints',
    descriptionEs: 'Recubrimiento epóxico de alta resistencia a la humedad, abrasión y productos químicos.',
    descriptionEn: 'Epoxy coating with high resistance to humidity, abrasion, and mild chemicals.',
    price: 11.67,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.7,
    reviewsCount: 168,
    image: '/productIMG/1772846539545.png',
    featured: false,
    stock: 23
  },
  {
    id: 'prod-37',
    nameEs: 'ZASC Restaurador y Renovador de Plásticos',
    nameEn: 'ZASC Plastic Restorer Renovator',
    category: 'paints',
    descriptionEs: 'Fórmula de alta resistencia que restaura y renueva plásticos quemados por el sol.',
    descriptionEn: 'Heavy-duty formula that restores and renews sun-faded plastic surfaces.',
    price: 15.24,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.0,
    reviewsCount: 93,
    image: '/productIMG/1772846592813.png',
    featured: false,
    stock: 52
  },
  {
    id: 'prod-38',
    nameEs: 'ZASC Soplador de Aire Comprimido',
    nameEn: 'ZASC Heavy-Duty Air Duster',
    category: 'paints',
    descriptionEs: 'Lata de aire comprimido de alta presión para limpieza de polvo en equipos y teclados.',
    descriptionEn: 'High-pressure compressed air can for dusting electronic equipment and keyboards.',
    price: 21.35,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.8,
    reviewsCount: 304,
    image: '/productIMG/1772846639516.png',
    featured: false,
    stock: 39
  },
  {
    id: 'prod-39',
    nameEs: 'Multilac Impermeabilizante para Fachadas',
    nameEn: 'Multilac Facade Waterproofing Sealer',
    category: 'paints',
    descriptionEs: 'Impermeabilizante concentrado base agua que protege muros exteriores contra lluvia y erosión.',
    descriptionEn: 'Concentrated water-based waterproofing that protects exterior walls from rain and erosion.',
    price: 47.06,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.8,
    reviewsCount: 193,
    image: '/productIMG/1772847041009.png',
    featured: false,
    stock: 116
  },
  {
    id: 'prod-40',
    nameEs: 'Quimicolor Auto-Cryl Laca Acrílica',
    nameEn: 'Quimicolor Auto-Cryl Acrylic Lacquer',
    category: 'paints',
    descriptionEs: 'Laca acrílica automotriz de excelente calidad, secado rápido y alto brillo.',
    descriptionEn: 'Automotive acrylic lacquer of excellent quality, fast drying, and high gloss.',
    price: 46.41,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 162,
    image: '/productIMG/1772847087557.png',
    featured: false,
    stock: 32
  },
  {
    id: 'prod-41',
    nameEs: 'Pegatanke Soldadura al Frío Acero',
    nameEn: 'Pegatanke Cold Steel Weld',
    category: 'paints',
    descriptionEs: 'Pegamento epóxico con carga metálica de acero para reparaciones de extrema resistencia.',
    descriptionEn: 'Epoxy adhesive with steel metal filler for extreme-strength repairs.',
    price: 38.96,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 5.0,
    reviewsCount: 70,
    image: '/productIMG/1772847171507.png',
    featured: false,
    stock: 70
  },
  {
    id: 'prod-42',
    nameEs: 'Paños de Microfibra Multiusos (3 unidades)',
    nameEn: 'All-Purpose Microfiber Cloths (3-Pack)',
    category: 'paints',
    descriptionEs: 'Paños suaves y absorbentes para la limpieza de interiores de autos, hogar y oficina.',
    descriptionEn: 'Soft and absorbent cloths for cleaning car interiors, homes, and offices.',
    price: 50.42,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.4,
    reviewsCount: 159,
    image: '/productIMG/1772847267675.png',
    featured: false,
    stock: 82
  },
  {
    id: 'prod-43',
    nameEs: 'Matrix Paños de Microfibra (3 Bolsillos)',
    nameEn: 'Matrix Microfiber Cloths (3-Pocket Pack)',
    category: 'paints',
    descriptionEs: 'Paños de microfibra de alta absorción y diseño sin rayaduras para pulir y limpiar.',
    descriptionEn: 'High-absorption, non-scratch microfiber cloths for polishing and cleaning.',
    price: 55.27,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.8,
    reviewsCount: 15,
    image: '/productIMG/1772847279349.png',
    featured: false,
    stock: 45
  },
  {
    id: 'prod-44',
    nameEs: 'Espátula Metálica Ferca',
    nameEn: 'Ferca Metal Spatula Scraper',
    category: 'paints',
    descriptionEs: 'Espátula metálica resistente para remover pintura, masilla y preparar superficies.',
    descriptionEn: 'Sturdy metal scraper spatula to remove paint, putty, and prepare surfaces.',
    price: 27.13,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 258,
    image: '/productIMG/1772847446128.png',
    featured: false,
    stock: 23
  },
  {
    id: 'prod-45',
    nameEs: 'Matrix Guantes Multiusos de Látex',
    nameEn: 'Matrix Latex Utility Gloves',
    category: 'paints',
    descriptionEs: 'Guantes de látex extra flexibles y resistentes para tareas domésticas e industriales.',
    descriptionEn: 'Extra flexible and resistant latex gloves for household and industrial tasks.',
    price: 14.03,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.0,
    reviewsCount: 204,
    image: '/productIMG/1772847529916.png',
    featured: false,
    stock: 57
  },
  {
    id: 'prod-46',
    nameEs: 'ZASC Juego de Coples y Conectores Rápidos',
    nameEn: 'ZASC Quick Coupler and Connector Kit',
    category: 'paints',
    descriptionEs: 'Juego de 5 piezas de coples rápidos para herramientas neumáticas y compresores.',
    descriptionEn: '5-piece quick coupler set for pneumatic tools and compressors.',
    price: 55.66,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 47,
    image: '/productIMG/1772847568650.png',
    featured: false,
    stock: 107
  },
  {
    id: 'prod-47',
    nameEs: 'Manpica Pintura de Óleo Brillante',
    nameEn: 'Manpica Gloss Oil Paint',
    category: 'paints',
    descriptionEs: 'Pintura alquídica al óleo para proteger y embellecer rejas, puertas y superficies metálicas.',
    descriptionEn: 'Oil-based alkyd paint to protect and beautify gates, doors, and metal surfaces.',
    price: 11.55,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.7,
    reviewsCount: 253,
    image: '/productIMG/1772847622042.png',
    featured: false,
    stock: 57
  },
  {
    id: 'prod-48',
    nameEs: 'Manpica Pintura de Caucho Mate Amarillo',
    nameEn: 'Manpica Yellow Matte Rubber Paint',
    category: 'paints',
    descriptionEs: 'Pintura de emulsión base agua con acabado mate decorativo para paredes y techos.',
    descriptionEn: 'Water-based emulsion paint with decorative matte finish for walls and ceilings.',
    price: 49.49,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.8,
    reviewsCount: 165,
    image: '/productIMG/1772847722425.png',
    featured: false,
    stock: 47
  },
  {
    id: 'prod-49',
    nameEs: 'Montana Pintura Brillo de Seda Satinada',
    nameEn: 'Montana Satin Silk Glow Paint',
    category: 'paints',
    descriptionEs: 'Pintura emulsionada poliacrílica con acabado satinado tipo seda de fácil limpieza.',
    descriptionEn: 'Polyacrylic emulsion paint with a silk satin finish that is easy to clean.',
    price: 45.20,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.9,
    reviewsCount: 295,
    image: '/productIMG/1772847757822.png',
    featured: false,
    stock: 61
  },
  {
    id: 'prod-50',
    nameEs: 'Montana 2000 Esmalte Alquídico Brillante',
    nameEn: 'Montana 2000 Gloss Alkyd Enamel',
    category: 'paints',
    descriptionEs: 'Esmalte sintético brillante para protección de estructuras domésticas e industriales.',
    descriptionEn: 'Glossy synthetic enamel for protection of household and industrial structures.',
    price: 14.50,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.4,
    reviewsCount: 84,
    image: '/productIMG/1772847798393.png',
    featured: false,
    stock: 116
  },
  {
    id: 'prod-51',
    nameEs: 'Quimicolor Pintura Súper Acrovinílica',
    nameEn: 'Quimicolor Super Acrovinyl Paint',
    category: 'paints',
    descriptionEs: 'Pintura vinil-acrílica lavable para interiores y exteriores de alto cubrimiento.',
    descriptionEn: 'Washable vinyl-acrylic paint for interior and exterior with high coverage.',
    price: 24.59,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.1,
    reviewsCount: 57,
    image: '/productIMG/1772847836460.png',
    featured: false,
    stock: 92
  },
  {
    id: 'prod-52',
    nameEs: 'Maxytone Clear 990 Barniz Automotriz',
    nameEn: 'Maxytone Clear 990 Automotive Clearcoat',
    category: 'paints',
    descriptionEs: 'Barniz transparente automotriz de alto brillo y secado rápido para repintado.',
    descriptionEn: 'High-gloss, fast-drying automotive clearcoat for professional refinish.',
    price: 31.79,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 241,
    image: '/productIMG/1772847890553.png',
    featured: false,
    stock: 61
  },
  {
    id: 'prod-53',
    nameEs: 'Masilla Rápida Mulod Quick Putty',
    nameEn: 'Mulod Quick Putty',
    category: 'paints',
    descriptionEs: 'Masilla monocomponente de secado ultrarrápido para corregir pequeñas imperfecciones.',
    descriptionEn: 'One-component ultra-fast drying putty to correct small surface imperfections.',
    price: 37.89,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.7,
    reviewsCount: 239,
    image: '/productIMG/1772914453529.png',
    featured: false,
    stock: 51
  },
  {
    id: 'prod-54',
    nameEs: 'Poliescol Impercryl P-7 Revestimiento Especializado',
    nameEn: 'Poliescol Impercryl P-7 Specialized Coating',
    category: 'paints',
    descriptionEs: 'Revestimiento protector de alta tecnología para fachadas y superficies de concreto.',
    descriptionEn: 'High-tech protective coating for facades and concrete surfaces.',
    price: 28.21,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 173,
    image: '/productIMG/1772914496859.png',
    featured: false,
    stock: 58
  },
  {
    id: 'prod-55',
    nameEs: 'Poliescol Impercryl Sellador Acrílico (1/4 Galón)',
    nameEn: 'Poliescol Impercryl Acrylic Sealer (1/4 Gal)',
    category: 'paints',
    descriptionEs: 'Sellador acrílico protector que evita la penetración de humedad en mampostería.',
    descriptionEn: 'Acrylic protective sealer that prevents moisture penetration in masonry.',
    price: 42.83,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.1,
    reviewsCount: 110,
    image: '/productIMG/1772914548315.png',
    featured: false,
    stock: 114
  },
  {
    id: 'prod-56',
    nameEs: 'Primer de Alto Relleno Automotriz',
    nameEn: 'High-Build Automotive Primer Surfacer',
    category: 'paints',
    descriptionEs: 'Aparejo de alto relleno con excelente lijabilidad y adherencia para chapa.',
    descriptionEn: 'High-build primer surfacer with excellent sandability and metal adhesion.',
    price: 10.34,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.7,
    reviewsCount: 62,
    image: '/productIMG/1772914590058.png',
    featured: false,
    stock: 118
  },
  {
    id: 'prod-57',
    nameEs: 'Menequini Barniz Transparente para Madera',
    nameEn: 'Menequini Clear Wood Varnish',
    category: 'paints',
    descriptionEs: 'Barniz transparente alquídico para madera con filtro solar y excelente brillo.',
    descriptionEn: 'Clear alkyd wood varnish with solar filter and excellent gloss.',
    price: 15.16,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.7,
    reviewsCount: 261,
    image: '/productIMG/1772914699231.png',
    featured: false,
    stock: 51
  },
  {
    id: 'prod-58',
    nameEs: 'Barniz Teñido Caoba Claro',
    nameEn: 'Light Mahogany Stained Varnish',
    category: 'paints',
    descriptionEs: 'Barniz con tinte color caoba claro para embellecer y proteger muebles de madera.',
    descriptionEn: 'Varnish with light mahogany stain to beautify and protect wood furniture.',
    price: 25.63,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.7,
    reviewsCount: 211,
    image: '/productIMG/1772914741076.png',
    featured: false,
    stock: 47
  },
  {
    id: 'prod-59',
    nameEs: 'VP Pinturas Esmalte de Alta Resistencia',
    nameEn: 'VP Paints High Resistance Enamel',
    category: 'paints',
    descriptionEs: 'Esmalte brillante premium para exteriores con máxima resistencia a la intemperie.',
    descriptionEn: 'Premium exterior gloss enamel with maximum weather resistance.',
    price: 22.49,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.9,
    reviewsCount: 19,
    image: '/productIMG/1772914816641.png',
    featured: false,
    stock: 29
  },
  {
    id: 'prod-60',
    nameEs: 'Manpica Manpi-Traf Pintura de Tráfico',
    nameEn: 'Manpica Manpi-Traf Traffic Paint',
    category: 'paints',
    descriptionEs: 'Pintura para señalización vial de secado rápido y excelente resistencia a la abrasión.',
    descriptionEn: 'Traffic marking paint with fast drying and excellent abrasion resistance.',
    price: 55.61,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.8,
    reviewsCount: 84,
    image: '/productIMG/1772914884047.png',
    featured: false,
    stock: 80
  },
  {
    id: 'prod-61',
    nameEs: 'Catalizador Epóxico Cromas',
    nameEn: 'Cromas Epoxy Catalyst Activator',
    category: 'paints',
    descriptionEs: 'Agente endurecedor para pinturas y masillas epóxicas de uso industrial y automotriz.',
    descriptionEn: 'Hardener agent for epoxy paints and fillers in industrial and automotive use.',
    price: 51.17,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.5,
    reviewsCount: 140,
    image: '/productIMG/1772914940022.png',
    featured: false,
    stock: 118
  },
  {
    id: 'prod-62',
    nameEs: 'Matrix Paños de Microfibra (3 unidades)',
    nameEn: 'Matrix Microfiber Cloths (3-Pack)',
    category: 'paints',
    descriptionEs: 'Paños suaves y absorbentes para la limpieza de interiores de autos, hogar y oficina.',
    descriptionEn: 'Soft and absorbent cloths for cleaning car interiors, homes, and offices.',
    price: 11.80,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.4,
    reviewsCount: 180,
    image: '/productIMG/1772915082945.png',
    featured: false,
    stock: 110
  },
  {
    id: 'prod-63',
    nameEs: 'Pinturas Cromas Aluminio Difuso',
    nameEn: 'Cromas Paints Diffuse Aluminum Paint',
    category: 'paints',
    descriptionEs: 'Pintura protectora anticorrosiva con acabado de brillo metálico aluminio.',
    descriptionEn: 'Anticorrosive protective paint with a metallic aluminum gloss finish.',
    price: 12.01,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.1,
    reviewsCount: 157,
    image: '/productIMG/1772915136463.png',
    featured: false,
    stock: 49
  },
  {
    id: 'prod-64',
    nameEs: 'Primer de Alto Relleno Automotriz',
    nameEn: 'High-Build Automotive Primer Surfacer',
    category: 'paints',
    descriptionEs: 'Aparejo de alto relleno con excelente lijabilidad y adherencia para chapa.',
    descriptionEn: 'High-build primer surfacer with excellent sandability and metal adhesion.',
    price: 56.88,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.1,
    reviewsCount: 283,
    image: '/productIMG/1772915171655.png',
    featured: false,
    stock: 56
  },
  {
    id: 'prod-65',
    nameEs: 'Abracol Abrawood Lija para Madera',
    nameEn: 'Abracol Abrawood Wood Sandpaper',
    category: 'paints',
    descriptionEs: 'Papel de lija de grano seleccionado para desbastar y pulir madera y barniz.',
    descriptionEn: 'Selected grit sandpaper for sanding and polishing wood and varnish finishes.',
    price: 57.64,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.7,
    reviewsCount: 12,
    image: '/productIMG/1772915204005.png',
    featured: false,
    stock: 57
  },
  {
    id: 'prod-66',
    nameEs: 'Soplador de Aire Comprimido Heavy-Duty',
    nameEn: 'Heavy-Duty Compressed Air Duster',
    category: 'paints',
    descriptionEs: 'Lata de aire comprimido de alta presión para limpieza de polvo en equipos y teclados.',
    descriptionEn: 'High-pressure compressed air can for dusting electronic equipment and keyboards.',
    price: 46.92,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 44,
    image: '/productIMG/1772915352127.png',
    featured: false,
    stock: 99
  },

  {
    id: 'prod-68',
    nameEs: 'PPV Class Pintura de Esmalte Negro',
    nameEn: 'PPV Class Black Enamel Paint',
    category: 'paints',
    descriptionEs: 'Esmalte brillante alquídico de alta adherencia y durabilidad, acabado negro intenso.',
    descriptionEn: 'High-adhesion, high-durability glossy alkyd enamel in a deep black finish.',
    price: 34.69,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 5.0,
    reviewsCount: 105,
    image: '/productIMG/20260310_112236.jpg',
    featured: false,
    stock: 39
  },
  {
    id: 'prod-69',
    nameEs: 'Solintex Plástica Profesional Celeste',
    nameEn: 'Solintex Professional Plastic Paint Light Blue',
    category: 'paints',
    descriptionEs: 'Pintura plástica premium color celeste para acabados de alta durabilidad en interiores y exteriores.',
    descriptionEn: 'Premium light blue plastic paint for high durability finishes on interior and exterior walls.',
    price: 25.66,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 170,
    image: '/productIMG/IMG_20260304_133608_342.webp',
    featured: false,
    stock: 25
  }
];

export const FAQS_DICT: FAQItem[] = [
  {
    questionEs: '¿Qué tipo de pintura debo usar para mi living o recámara?',
    questionEn: 'What type of paint should I use for my living room or bedroom?',
    answerEs: 'Para interiores de uso frecuente como recámaras y salas de estar, recomendamos nuestra Pintura Látex Super-Acrílica Premium con acabado Satín o Mate de Colormar. Es lavable, tiene un olor bajísimo (ideal para habitar el espacio rápido) y cubre imperfecciones excepcionalmente.',
    answerEn: 'For highly-trafficked interior spaces like bedrooms and family rooms, we recommend our Colormar Premium Super-Acrylic Latex in a Satin or Matte finish. It is scrubbable, low-odor (allowing fast re-occupancy), and hides wall minor imperfections beautifully.',
  },
  {
    questionEs: '¿Cómo calculo cuántos galones de pintura necesito comprar?',
    questionEn: 'How do I calculate how many gallons of paint I need to purchase?',
    answerEs: '¡Es súper sencillo! Puedes usar la Calculadora de Cobertura Interactiva que diseñamos especialmente para ti en esta página. Solo mide el ancho y alto de tus paredes, descuenta puertas y ventanas, ¡y el sistema te dirá la cifra exacta de galones que debes adquirir!',
    answerEn: 'It\'s easy! You can use our Interactive Paint Coverage Calculator built right into this page. Just input the width and height of your walls, subtract doors and windows, and our system instantly displays the exact gallon quantity to order!',
  },
  {
    questionEs: '¿Qué es el sistema de mezcla personalizada de Colormar?',
    questionEn: 'What is Colormar\'s Custom Paint Tinting System?',
    answerEs: 'En Colormar podemos modular cualquier tono del espectro. Si te inspira el exótico azul de nuestra paleta tucán, o si traes una muestra textil, con nuestro laboratorio computerizado de calibrado espectrofotométrico conseguimos la pintura exacta en la base que desees (mate, satinada o brillante).',
    answerEn: 'At Colormar we can formulate any tone under the spectrum. Whether you are inspired by our exotic toucan blue or bring a textile swatch, our spectrophotometric computerized laboratory obtains the exact match in the finish you prefer (matte, satin, or gloss).',
  },
  {
    questionEs: '¿La pintura exterior resiste filtraciones por lluvia y humedad?',
    questionEn: 'Does the exterior paint resist rain filtration and heavy humidity?',
    answerEs: 'Totalmente. Nuestra Pintura Exterior tiene resinas elastoméricas y tecnología UV-Blocker para expandirse y contraerse con el calor, sellando microfisuras estructurales de la pared y bloqueando el ingreso del agua y la formación de moho u hongos.',
    answerEn: 'Absolutely. Our Exterior Paint is manufactured with elastomeric resins and UV-Blocker technology to expand and contract with high temperature, sealing architectural micro-cracks on walls while blocking rain intrusion and the growth of mold or fungus.',
  },
  {
    questionEs: '¿Envían a domicilio o puedo retirar mi pedido en tienda?',
    questionEn: 'Do you deliver or can I pick up my order in-store?',
    answerEs: 'Ofrecemos ambas opciones. Al solicitar tu cotización o mezcla, puedes elegir despacho a domicilio ultra-rápido en 24 horas, o elegir el retiro Express en nuestra tienda central, donde te esperaremos con el café listo y tu pintura mezclada.',
    answerEn: 'We offer both options. When requesting a quote or custom paint order, you can choose 24-hour ultra-fast home delivery, or select Express Store Pickup, where we will wait for you with warm coffee and your custom paint fully mixed.'
  }
];
