/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ColorPaletteEntry, Product, FAQItem } from './types';

export const COLOR_PALETTE: ColorPaletteEntry[] = [
  {
    id: 'toucan-orange',
    nameEs: 'Naranja Tucán',
    nameEn: 'Toucan Orange',
    hex: '#F97316',
    categoryEs: 'Paleta Exótica',
    categoryEn: 'Exotic Palette',
    descriptionEs: 'Un naranja sumamente energético y cálido inspirado en el pico de nuestro tucán.',
    descriptionEn: 'An energetic and warm orange inspired by our toucan\'s iconic bill.',
    isToucanColor: true
  },
  {
    id: 'tropical-yellow',
    nameEs: 'Amarillo Tropical',
    nameEn: 'Tropical Yellow',
    hex: '#FACC15',
    categoryEs: 'Paleta Exótica',
    categoryEn: 'Exotic Palette',
    descriptionEs: 'Luminoso y vibrante como el sol de la selva ecuatorial, perfecto para crear ambientes llenos de vida.',
    descriptionEn: 'Bright and vibrant like the equatorial jungle sun, perfect for creating lively spaces.',
    isToucanColor: true
  },
  {
    id: 'coral-red',
    nameEs: 'Rojo Coral',
    nameEn: 'Coral Red',
    hex: '#EF4444',
    categoryEs: 'Paleta Exótica',
    categoryEn: 'Exotic Palette',
    descriptionEs: 'El atrevido y pasional matiz rojo que acentúa las puntas del plumaje y pico del tucán.',
    descriptionEn: 'The bold, passionate red hue that highlights the tips of the toucan\'s features.',
    isToucanColor: true
  },
  {
    id: 'jungle-cyan',
    nameEs: 'Celeste Selva',
    nameEn: 'Jungle Cyan',
    hex: '#06B6D4',
    categoryEs: 'Paleta Exótica',
    categoryEn: 'Exotic Palette',
    descriptionEs: 'Un celeste refrescante e innovador, inspirado en los destellos magnéticos alrededor de los ojos de nuestro tucán.',
    descriptionEn: 'A refreshing and innovative light blue, inspired by the magnetic glow around our toucan\'s eyes.',
    isToucanColor: true
  },
  {
    id: 'ocean-blue',
    nameEs: 'Azul Marino Colormar',
    nameEn: 'Colormar Deep Blue',
    hex: '#1E3A8A',
    categoryEs: 'Clásicos Imperiales',
    categoryEn: 'Imperial Classics',
    descriptionEs: 'Elegante, equilibrado y profundo. Ideal para fachadas sofisticadas y paredes de acento.',
    descriptionEn: 'Elegant, balanced, and deep. Ideal for sophisticated facades and accent walls.',
  },
  {
    id: 'emerald-forest',
    nameEs: 'Verde Esmeralda',
    nameEn: 'Emerald Forest',
    hex: '#10B981',
    categoryEs: 'Naturaleza Orgánica',
    categoryEn: 'Organic Nature',
    descriptionEs: 'Un tono orgánico y pacífico que imita la opulencia de la vegetación selvática húmeda.',
    descriptionEn: 'An organic and peaceful shade echoing the richness of the wet rainforest canopy.',
  },
  {
    id: 'concrete-gray',
    nameEs: 'Gris Cemento',
    nameEn: 'Concrete Gray',
    hex: '#94A3B8',
    categoryEs: 'Minimalismo Urbano',
    categoryEn: 'Urban Minimalism',
    descriptionEs: 'El equilibrio industrial perfecto. Refinado, moderno y altamente versátil para interiores vanguardistas.',
    descriptionEn: 'The perfect industrial balance. Refined, modern, and highly versatile for vanguard interiors.',
  },
  {
    id: 'pure-alabaster',
    nameEs: 'Blanco Alabastro',
    nameEn: 'Alabaster White',
    hex: '#F8FAFC',
    categoryEs: 'Minimalismo Urbano',
    categoryEn: 'Urban Minimalism',
    descriptionEs: 'Un blanco puro y luminoso que multiplica el rebote de la luz natural de tus estancias.',
    descriptionEn: 'A pure, luminous white that multiplies natural light bounce inside your rooms.',
  }
];

export const PRODUCTS: Product[] = [
  {
    id: 'prod-0',
    nameEs: 'Producto Colormar 1',
    nameEn: 'Colormar Product 1',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 44.52,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.2,
    reviewsCount: 227,
    image: '/productIMG/1772643756103.png',
    featured: true,
    stock: 64
  },
  {
    id: 'prod-1',
    nameEs: 'Producto Colormar 2',
    nameEn: 'Colormar Product 2',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 16.18,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 270,
    image: '/productIMG/1772643877934.png',
    featured: true,
    stock: 25
  },
  {
    id: 'prod-2',
    nameEs: 'Thinner Acrílico Quiminter',
    nameEn: 'Quiminter Acrylic Thinner',
    category: 'paints',
    descriptionEs: 'Solvente de alta pureza para dilución de pinturas acrílicas.',
    descriptionEn: 'High-purity solvent for acrylic paint dilution.',
    price: 40.17,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 207,
    image: '/productIMG/1772644108859.png',
    featured: true,
    stock: 21
  },
  {
    id: 'prod-3',
    nameEs: 'Producto Colormar 4',
    nameEn: 'Colormar Product 4',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 50.06,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 90,
    image: '/productIMG/1772644164759.png',
    featured: true,
    stock: 86
  },
  {
    id: 'prod-4',
    nameEs: 'Producto Colormar 5',
    nameEn: 'Colormar Product 5',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 25.46,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.9,
    reviewsCount: 290,
    image: '/productIMG/1772644234872.png',
    featured: true,
    stock: 20
  },
  {
    id: 'prod-5',
    nameEs: 'Producto Colormar 6',
    nameEn: 'Colormar Product 6',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 14.21,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.1,
    reviewsCount: 58,
    image: '/productIMG/1772644294053.png',
    featured: false,
    stock: 78
  },
  {
    id: 'prod-6',
    nameEs: 'Producto Colormar 7',
    nameEn: 'Colormar Product 7',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 33.47,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.2,
    reviewsCount: 120,
    image: '/productIMG/1772644367078.png',
    featured: false,
    stock: 88
  },
  {
    id: 'prod-7',
    nameEs: 'Producto Colormar 8',
    nameEn: 'Colormar Product 8',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 23.75,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.4,
    reviewsCount: 22,
    image: '/productIMG/1772644410638.png',
    featured: false,
    stock: 57
  },
  {
    id: 'prod-8',
    nameEs: 'Producto Colormar 9',
    nameEn: 'Colormar Product 9',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 34.53,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.4,
    reviewsCount: 187,
    image: '/productIMG/1772644482091.png',
    featured: false,
    stock: 48
  },
  {
    id: 'prod-9',
    nameEs: 'Producto Colormar 10',
    nameEn: 'Colormar Product 10',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 16.98,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.5,
    reviewsCount: 113,
    image: '/productIMG/1772644534883.png',
    featured: false,
    stock: 66
  },
  {
    id: 'prod-10',
    nameEs: 'Producto Colormar 11',
    nameEn: 'Colormar Product 11',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 11.71,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.9,
    reviewsCount: 217,
    image: '/productIMG/1772644596774.png',
    featured: false,
    stock: 85
  },
  {
    id: 'prod-11',
    nameEs: 'Producto Colormar 12',
    nameEn: 'Colormar Product 12',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 18.36,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 130,
    image: '/productIMG/1772644652214.png',
    featured: false,
    stock: 65
  },
  {
    id: 'prod-12',
    nameEs: 'Producto Colormar 13',
    nameEn: 'Colormar Product 13',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 15.22,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.2,
    reviewsCount: 173,
    image: '/productIMG/1772644713031.png',
    featured: false,
    stock: 83
  },
  {
    id: 'prod-13',
    nameEs: 'Producto Colormar 14',
    nameEn: 'Colormar Product 14',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 50.59,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.2,
    reviewsCount: 193,
    image: '/productIMG/1772644823755.png',
    featured: false,
    stock: 114
  },
  {
    id: 'prod-14',
    nameEs: 'Producto Colormar 15',
    nameEn: 'Colormar Product 15',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 42.01,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 184,
    image: '/productIMG/1772644893283.png',
    featured: false,
    stock: 48
  },
  {
    id: 'prod-15',
    nameEs: 'Producto Colormar 16',
    nameEn: 'Colormar Product 16',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 20.46,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.1,
    reviewsCount: 249,
    image: '/productIMG/1772645013474.png',
    featured: false,
    stock: 59
  },
  {
    id: 'prod-16',
    nameEs: 'Producto Colormar 17',
    nameEn: 'Colormar Product 17',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 27.25,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 5.0,
    reviewsCount: 164,
    image: '/productIMG/1772645068843.png',
    featured: false,
    stock: 117
  },
  {
    id: 'prod-17',
    nameEs: 'Producto Colormar 18',
    nameEn: 'Colormar Product 18',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 31.17,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.8,
    reviewsCount: 200,
    image: '/productIMG/1772645167680.png',
    featured: false,
    stock: 32
  },
  {
    id: 'prod-18',
    nameEs: 'Producto Colormar 19',
    nameEn: 'Colormar Product 19',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 55.32,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.4,
    reviewsCount: 152,
    image: '/productIMG/1772737414926.png',
    featured: false,
    stock: 26
  },
  {
    id: 'prod-19',
    nameEs: 'Producto Colormar 20',
    nameEn: 'Colormar Product 20',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 21.57,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 46,
    image: '/productIMG/1772737700379.png',
    featured: false,
    stock: 109
  },
  {
    id: 'prod-20',
    nameEs: 'Producto Colormar 21',
    nameEn: 'Colormar Product 21',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 44.40,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 78,
    image: '/productIMG/1772737792843.png',
    featured: false,
    stock: 105
  },
  {
    id: 'prod-21',
    nameEs: 'Producto Colormar 22',
    nameEn: 'Colormar Product 22',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 35.20,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.9,
    reviewsCount: 112,
    image: '/productIMG/1772737899052.png',
    featured: false,
    stock: 97
  },
  {
    id: 'prod-22',
    nameEs: 'Producto Colormar 23',
    nameEn: 'Colormar Product 23',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 53.50,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 296,
    image: '/productIMG/1772737967937.png',
    featured: false,
    stock: 50
  },
  {
    id: 'prod-23',
    nameEs: 'Producto Colormar 24',
    nameEn: 'Colormar Product 24',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 14.64,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.5,
    reviewsCount: 161,
    image: '/productIMG/1772738076661.png',
    featured: false,
    stock: 49
  },
  {
    id: 'prod-24',
    nameEs: 'Producto Colormar 25',
    nameEn: 'Colormar Product 25',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 45.96,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.2,
    reviewsCount: 129,
    image: '/productIMG/1772738153356.png',
    featured: false,
    stock: 57
  },
  {
    id: 'prod-25',
    nameEs: 'Producto Colormar 26',
    nameEn: 'Colormar Product 26',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 24.71,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 257,
    image: '/productIMG/1772738246923.png',
    featured: false,
    stock: 53
  },
  {
    id: 'prod-26',
    nameEs: 'Producto Colormar 27',
    nameEn: 'Colormar Product 27',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 15.09,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.5,
    reviewsCount: 278,
    image: '/productIMG/1772738324087.png',
    featured: false,
    stock: 64
  },
  {
    id: 'prod-27',
    nameEs: 'Producto Colormar 28',
    nameEn: 'Colormar Product 28',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 16.08,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.8,
    reviewsCount: 43,
    image: '/productIMG/1772738373979.png',
    featured: false,
    stock: 115
  },
  {
    id: 'prod-28',
    nameEs: 'Producto Colormar 29',
    nameEn: 'Colormar Product 29',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 20.20,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 202,
    image: '/productIMG/1772738428354.png',
    featured: false,
    stock: 56
  },
  {
    id: 'prod-29',
    nameEs: 'Producto Colormar 30',
    nameEn: 'Colormar Product 30',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 45.56,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 74,
    image: '/productIMG/1772738497559.png',
    featured: false,
    stock: 34
  },
  {
    id: 'prod-30',
    nameEs: 'Producto Colormar 31',
    nameEn: 'Colormar Product 31',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 22.42,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.2,
    reviewsCount: 180,
    image: '/productIMG/1772738556537.png',
    featured: false,
    stock: 22
  },
  {
    id: 'prod-31',
    nameEs: 'Producto Colormar 32',
    nameEn: 'Colormar Product 32',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 36.45,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 152,
    image: '/productIMG/1772738605164.png',
    featured: false,
    stock: 31
  },
  {
    id: 'prod-32',
    nameEs: 'Producto Colormar 33',
    nameEn: 'Colormar Product 33',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 49.45,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.1,
    reviewsCount: 232,
    image: '/productIMG/1772738665880.png',
    featured: false,
    stock: 37
  },
  {
    id: 'prod-33',
    nameEs: 'Producto Colormar 34',
    nameEn: 'Colormar Product 34',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 13.36,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 244,
    image: '/productIMG/1772738718822.png',
    featured: false,
    stock: 59
  },
  {
    id: 'prod-34',
    nameEs: 'Producto Colormar 35',
    nameEn: 'Colormar Product 35',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 59.51,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 152,
    image: '/productIMG/1772738773998.png',
    featured: false,
    stock: 69
  },
  {
    id: 'prod-35',
    nameEs: 'Producto Colormar 36',
    nameEn: 'Colormar Product 36',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 43.24,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 183,
    image: '/productIMG/1772846488149.png',
    featured: false,
    stock: 48
  },
  {
    id: 'prod-36',
    nameEs: 'Producto Colormar 37',
    nameEn: 'Colormar Product 37',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 11.67,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.7,
    reviewsCount: 168,
    image: '/productIMG/1772846539545.png',
    featured: false,
    stock: 23
  },
  {
    id: 'prod-37',
    nameEs: 'Producto Colormar 38',
    nameEn: 'Colormar Product 38',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 15.24,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.0,
    reviewsCount: 93,
    image: '/productIMG/1772846592813.png',
    featured: false,
    stock: 52
  },
  {
    id: 'prod-38',
    nameEs: 'Producto Colormar 39',
    nameEn: 'Colormar Product 39',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 21.35,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.8,
    reviewsCount: 304,
    image: '/productIMG/1772846639516.png',
    featured: false,
    stock: 39
  },
  {
    id: 'prod-39',
    nameEs: 'Producto Colormar 40',
    nameEn: 'Colormar Product 40',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 47.06,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.8,
    reviewsCount: 193,
    image: '/productIMG/1772847041009.png',
    featured: false,
    stock: 116
  },
  {
    id: 'prod-40',
    nameEs: 'Producto Colormar 41',
    nameEn: 'Colormar Product 41',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 46.41,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 162,
    image: '/productIMG/1772847087557.png',
    featured: false,
    stock: 32
  },
  {
    id: 'prod-41',
    nameEs: 'Producto Colormar 42',
    nameEn: 'Colormar Product 42',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 38.96,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 5.0,
    reviewsCount: 70,
    image: '/productIMG/1772847171507.png',
    featured: false,
    stock: 70
  },
  {
    id: 'prod-42',
    nameEs: 'Producto Colormar 43',
    nameEn: 'Colormar Product 43',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 50.42,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.4,
    reviewsCount: 159,
    image: '/productIMG/1772847267675.png',
    featured: false,
    stock: 82
  },
  {
    id: 'prod-43',
    nameEs: 'Producto Colormar 44',
    nameEn: 'Colormar Product 44',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 55.27,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.8,
    reviewsCount: 15,
    image: '/productIMG/1772847279349.png',
    featured: false,
    stock: 45
  },
  {
    id: 'prod-44',
    nameEs: 'Producto Colormar 45',
    nameEn: 'Colormar Product 45',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 27.13,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 258,
    image: '/productIMG/1772847446128.png',
    featured: false,
    stock: 23
  },
  {
    id: 'prod-45',
    nameEs: 'Producto Colormar 46',
    nameEn: 'Colormar Product 46',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 14.03,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.0,
    reviewsCount: 204,
    image: '/productIMG/1772847529916.png',
    featured: false,
    stock: 57
  },
  {
    id: 'prod-46',
    nameEs: 'Producto Colormar 47',
    nameEn: 'Colormar Product 47',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 55.66,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 47,
    image: '/productIMG/1772847568650.png',
    featured: false,
    stock: 107
  },
  {
    id: 'prod-47',
    nameEs: 'Producto Colormar 48',
    nameEn: 'Colormar Product 48',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 11.55,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.7,
    reviewsCount: 253,
    image: '/productIMG/1772847622042.png',
    featured: false,
    stock: 57
  },
  {
    id: 'prod-48',
    nameEs: 'Producto Colormar 49',
    nameEn: 'Colormar Product 49',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 49.49,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.8,
    reviewsCount: 165,
    image: '/productIMG/1772847722425.png',
    featured: false,
    stock: 47
  },
  {
    id: 'prod-49',
    nameEs: 'Producto Colormar 50',
    nameEn: 'Colormar Product 50',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 45.20,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.9,
    reviewsCount: 295,
    image: '/productIMG/1772847757822.png',
    featured: false,
    stock: 61
  },
  {
    id: 'prod-50',
    nameEs: 'Producto Colormar 51',
    nameEn: 'Colormar Product 51',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 14.50,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.4,
    reviewsCount: 84,
    image: '/productIMG/1772847798393.png',
    featured: false,
    stock: 116
  },
  {
    id: 'prod-51',
    nameEs: 'Producto Colormar 52',
    nameEn: 'Colormar Product 52',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 24.59,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.1,
    reviewsCount: 57,
    image: '/productIMG/1772847836460.png',
    featured: false,
    stock: 92
  },
  {
    id: 'prod-52',
    nameEs: 'Producto Colormar 53',
    nameEn: 'Colormar Product 53',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 31.79,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 241,
    image: '/productIMG/1772847890553.png',
    featured: false,
    stock: 61
  },
  {
    id: 'prod-53',
    nameEs: 'Producto Colormar 54',
    nameEn: 'Colormar Product 54',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 37.89,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.7,
    reviewsCount: 239,
    image: '/productIMG/1772914453529.png',
    featured: false,
    stock: 51
  },
  {
    id: 'prod-54',
    nameEs: 'Producto Colormar 55',
    nameEn: 'Colormar Product 55',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 28.21,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 173,
    image: '/productIMG/1772914496859.png',
    featured: false,
    stock: 58
  },
  {
    id: 'prod-55',
    nameEs: 'Producto Colormar 56',
    nameEn: 'Colormar Product 56',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 42.83,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.1,
    reviewsCount: 110,
    image: '/productIMG/1772914548315.png',
    featured: false,
    stock: 114
  },
  {
    id: 'prod-56',
    nameEs: 'Producto Colormar 57',
    nameEn: 'Colormar Product 57',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 10.34,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.7,
    reviewsCount: 62,
    image: '/productIMG/1772914590058.png',
    featured: false,
    stock: 118
  },
  {
    id: 'prod-57',
    nameEs: 'Producto Colormar 58',
    nameEn: 'Colormar Product 58',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 15.16,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.7,
    reviewsCount: 261,
    image: '/productIMG/1772914699231.png',
    featured: false,
    stock: 51
  },
  {
    id: 'prod-58',
    nameEs: 'Producto Colormar 59',
    nameEn: 'Colormar Product 59',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 25.63,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.7,
    reviewsCount: 211,
    image: '/productIMG/1772914741076.png',
    featured: false,
    stock: 47
  },
  {
    id: 'prod-59',
    nameEs: 'Producto Colormar 60',
    nameEn: 'Colormar Product 60',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 22.49,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.9,
    reviewsCount: 19,
    image: '/productIMG/1772914816641.png',
    featured: false,
    stock: 29
  },
  {
    id: 'prod-60',
    nameEs: 'Producto Colormar 61',
    nameEn: 'Colormar Product 61',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 55.61,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.8,
    reviewsCount: 84,
    image: '/productIMG/1772914884047.png',
    featured: false,
    stock: 80
  },
  {
    id: 'prod-61',
    nameEs: 'Producto Colormar 62',
    nameEn: 'Colormar Product 62',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 51.17,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.5,
    reviewsCount: 140,
    image: '/productIMG/1772914940022.png',
    featured: false,
    stock: 118
  },
  {
    id: 'prod-62',
    nameEs: 'Producto Colormar 63',
    nameEn: 'Colormar Product 63',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 11.80,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.4,
    reviewsCount: 180,
    image: '/productIMG/1772915082945.png',
    featured: false,
    stock: 110
  },
  {
    id: 'prod-63',
    nameEs: 'Producto Colormar 64',
    nameEn: 'Colormar Product 64',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 12.01,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.1,
    reviewsCount: 157,
    image: '/productIMG/1772915136463.png',
    featured: false,
    stock: 49
  },
  {
    id: 'prod-64',
    nameEs: 'Producto Colormar 65',
    nameEn: 'Colormar Product 65',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 56.88,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.1,
    reviewsCount: 283,
    image: '/productIMG/1772915171655.png',
    featured: false,
    stock: 56
  },
  {
    id: 'prod-65',
    nameEs: 'Producto Colormar 66',
    nameEn: 'Colormar Product 66',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 57.64,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.7,
    reviewsCount: 12,
    image: '/productIMG/1772915204005.png',
    featured: false,
    stock: 57
  },
  {
    id: 'prod-66',
    nameEs: 'Producto Colormar 67',
    nameEn: 'Colormar Product 67',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 46.92,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.6,
    reviewsCount: 44,
    image: '/productIMG/1772915352127.png',
    featured: false,
    stock: 99
  },
  {
    id: 'prod-67',
    nameEs: 'Producto Colormar 68',
    nameEn: 'Colormar Product 68',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 32.36,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 5.0,
    reviewsCount: 125,
    image: '/productIMG/20260302_132646.jpg',
    featured: false,
    stock: 72
  },
  {
    id: 'prod-68',
    nameEs: 'Producto Colormar 69',
    nameEn: 'Colormar Product 69',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 34.69,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 5.0,
    reviewsCount: 105,
    image: '/productIMG/20260310_112236.jpg',
    featured: false,
    stock: 39
  },
  {
    id: 'prod-69',
    nameEs: 'Producto Colormar 70',
    nameEn: 'Colormar Product 70',
    category: 'paints',
    descriptionEs: 'Acabado de alta gama con calidad profesional.',
    descriptionEn: 'High-end finish with professional quality.',
    price: 25.66,
    unitEs: 'Unidad',
    unitEn: 'Unit',
    rating: 4.3,
    reviewsCount: 170,
    image: '/productIMG/IMG_20260304_133608_342.webp',
    featured: false,
    stock: 25
  }
];

export const FAQS_DICT: FAQItem[] = [
  {
    questionEs: '¿Qué tipo de pintura debo usar para mi living o recámara?',
    questionEn: 'What type of paint should I use for my living room or bedroom?',
    answerEs: 'Para interiores de uso frecuente como recámaras y salas de estar, recomendamos nuestra Pintura Látex Super-Acrílica Premium con acabado Satín o Mate de Colormar. Es lavable, tiene un olor bajísimo (ideal para habitar el espacio rápido) y cubre imperfecciones excepcionalmente.',
    answerEn: 'For highly-trafficked interior spaces like bedrooms and family rooms, we recommend our Colormar Premium Super-Acrylic Latex in a Satin or Matte finish. It is scrubbable, low-odor (allowing fast re-occupancy), and hides wall minor imperfections beautifully.',
  },
  {
    questionEs: '¿Cómo calculo cuántos galones de pintura necesito comprar?',
    questionEn: 'How do I calculate how many gallons of paint I need to purchase?',
    answerEs: '¡Es súper sencillo! Puedes usar la Calculadora de Cobertura Interactiva que diseñamos especialmente para ti en esta página. Solo mide el ancho y alto de tus paredes, descuenta puertas y ventanas, ¡y el sistema te dirá la cifra exacta de galones que debes adquirir!',
    answerEn: 'It\'s easy! You can use our Interactive Paint Coverage Calculator built right into this page. Just input the width and height of your walls, subtract doors and windows, and our system instantly displays the exact gallon quantity to order!',
  },
  {
    questionEs: '¿Qué es el sistema de mezcla personalizada de Colormar?',
    questionEn: 'What is Colormar\'s Custom Paint Tinting System?',
    answerEs: 'En Colormar podemos modular cualquier tono del espectro. Si te inspira el exótico azul de nuestra paleta tucán, o si traes una muestra textil, con nuestro laboratorio computerizado de calibrado espectrofotométrico conseguimos la pintura exacta en la base que desees (mate, satinada o brillante).',
    answerEn: 'At Colormar we can formulate any tone under the spectrum. Whether you are inspired by our exotic toucan blue or bring a textile swatch, our spectrophotometric computerized laboratory obtains the exact match in the finish you prefer (matte, satin, or gloss).',
  },
  {
    questionEs: '¿La pintura exterior resiste filtraciones por lluvia y humedad?',
    questionEn: 'Does the exterior paint resist rain filtration and heavy humidity?',
    answerEs: 'Totalmente. Nuestra Pintura Exterior tiene resinas elastoméricas y tecnología UV-Blocker para expandirse y contraerse con el calor, sellando microfisuras estructurales de la pared y bloqueando el ingreso del agua y la formación de moho u hongos.',
    answerEn: 'Absolutely. Our Exterior Paint is manufactured with elastomeric resins and UV-Blocker technology to expand and contract with high temperature, sealing architectural micro-cracks on walls while blocking rain intrusion and the growth of mold or fungus.',
  },
  {
    questionEs: '¿Envían a domicilio o puedo retirar mi pedido en tienda?',
    questionEn: 'Do you deliver or can I pick up my order in-store?',
    answerEs: 'Ofrecemos ambas opciones. Al solicitar tu cotización o mezcla, puedes elegir despacho a domicilio ultra-rápido en 24 horas, o elegir el retiro Express en nuestra tienda central, donde te esperaremos con el café listo y tu pintura mezclada.',
    answerEn: 'We offer both options. When requesting a quote or custom paint order, you can choose 24-hour ultra-fast home delivery, or select Express Store Pickup, where we will wait for you with warm coffee and your custom paint fully mixed.'
  }
];
